version: '3'

services:
  web:
    build:
      context: '.'
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/questionnaire_app/
    ports:
      - '8000:8000'
    depends_on:
      - db-postgres
  db-postgres:
    image: postgres:13.1-alpine
    volumes:
      # - postgres_data:/var/lib/postgresql/data/
      - ./run/db_postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=questionnaire_app
      - POSTGRES_PASSWORD=questionnaire_app
      - POSTGRES_DB=questionnaire
    ports:
       - '5432:5432'