# Generated by Django 2.2.10 on 2021-06-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210618_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='choices', to='polls.Question', verbose_name='Poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='polls.Poll', verbose_name='Опрос'),
        ),
    ]
